name: Go-Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
      # 设置Go环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      # 安装golangci-lint
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --config=.golangci.yml
      # 运行golangci-lint
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.2.2
          args: --config=.golangci.yml
          verify: true  # 跳过 config verify
          only-new-issues: false
